# Clippy configuration
# Allow some common patterns that might be too strict
allow = [
    "clippy::module_name_repetitions",
    "clippy::multiple_crate_versions",
    "clippy::missing_errors_doc",
    "clippy::missing_panics_doc",
]

# Deny some important warnings
deny = [
    "clippy::unwrap_used",
    "clippy::expect_used",
    "clippy::panic",
    "clippy::unimplemented",
    "clippy::todo",
    "clippy::unreachable",
]

# Set some specific configurations
warn = [
    "clippy::all",
]

# Performance related
warn = [
    "clippy::perf",
    "clippy::style",
    "clippy::complexity",
    "clippy::correctness",
]
